---
- hosts: all
  roles:
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: licecap 
  - role: cask_package
    package_name: firefox 
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: chromium
  - role: cask_package
    package_name: java 
  - role: cask_package
    package_name: eclipse-java
  - role: brew_package
    package_name: graphicsmagick 
  - role: brew_package
    package_name: mysql 
  - role: pip_package
    package_name: tmuxp
